---
- name: Update and upgrade apt packages
  become: true
  ansible.builtin.apt:
    upgrade: true
    update_cache: true
    cache_valid_time: 86400 #One day
  when:
    - ansible_facts['os_family'] == "Debian"

- name: Update all packages for RHEL Family
  ansible.builtin.dnf:
    name: "*"
    state: latest # noqa package-latest
    update_cache: true
  when:
    - ansible_facts['os_family'] == "RedHat"

- name: Install gcloud pre-required packages
  ansible.builtin.package:
    name:
      - "apt-transport-https"
      - "ca-certificates"
      - "gnupg"
      - "curl"
    state: present
  become: true
  when:
    - ansible_facts['os_family'] == "Debian"

- name: Add GCloud key downloaded from URL to GCloud Keyring
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    keyring: /usr/share/keyrings/cloud.google.gpg
    state: present
  become: true
  when:
    - ansible_facts['os_family'] == "Debian"

- name: Add GCloud repository into sources list
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main"
    state: present
  become: true
  when:
    - ansible_facts['os_family'] == "Debian"

- name: Install Google Cloud CLI repository in RHEL Family
  ansible.builtin.yum_repository:
    name: "GoogleCloud-CLI"
    state: present
    description: "Google Cloud CLI"
    baseurl: "https://packages.cloud.google.com/yum/repos/cloud-sdk-el9-x86_64"
    gpgcheck: true
    gpgkey: "https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg"
  when:
    - ansible_facts['os_family'] == "RedHat"

- name: Update the repository cache and Install GCloud in Debian/Ubuntu family
  ansible.builtin.apt:
    name: "google-cloud-cli"
    update_cache: true
  become: true
  when:
    - ansible_facts['os_family'] == "Debian"

- name: Update the repository cache and Install GCloud in RHEL family
  ansible.builtin.dnf:
    name: "google-cloud-cli"
    state: present
    update_cache: true
  when:
    - ansible_facts['os_family'] == "RedHat"

- name: Install Additional Gcloud Packages
  ansible.builtin.package:
    name: "{{ gc_package }}"
    state: present
  become: true
  loop: "{{ gcloud_additional_components }}"
  loop_control:
    loop_var: gc_package
