---
- debug: var=ansible_os_family
- name: Load OS specific Vars file
  include_vars: "{{ item }}"
  with_first_found:
    - "os_specific_{{ ansible_os_family }}.yml"
    - "os_specific_default.yml"

- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day
  when:
    - ansible_os_family == 'Debian'

- name: Update and upgrade yum packages
  become: true
  yum:
    update_cache: yes
    name: '*'
    state: latest
  when:
    - ansible_os_family == 'RedHat'

- name: Install gcloud pre-required packages
  package:
    name:
      - "apt-transport-https"
      - "ca-certificates"
      - "gnupg"
      - "curl"
    state: present
  become: true

- name: Add GCloud key downloaded from URL to GCloud Keyring
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    keyring: /usr/share/keyrings/cloud.google.gpg
    state: present
  become: true

- name: Add GCloud repository into sources list
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main"
    state: present
  become: true

- name: Update the repository cache and Install GCloud on Host-Server
  ansible.builtin.apt:
    name: "google-cloud-cli"
    update_cache: yes
  become: true

- name: Install Additional Gcloud Packages
  package:
    name: "{{ gc_package }}"
    state: present
  become: true
  loop: "{{ gcloud_additional_components }}"
  loop_control:
    loop_var: gc_package
