---
- name: Check shell config
  ansible.builtin.stat:
    path: "{{ item.path }}"
  register: res

- name: Add path and completion to {{ item.path }}
  ansible.builtin.blockinfile:
    path: "{{ item.path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: GOOGLE_CLOUD_SDK"
    block: |
      source {{ gcloud_install_dir }}/google-cloud-sdk/path.{{ item.name }}.inc
      source {{ gcloud_install_dir }}/google-cloud-sdk/completion.{{ item.name }}.inc
    state: "{{ gcloud_state }}"
  when: res.stat.exists
