---
driver:
  name: podman
platforms:
  - name: "${MOLECULE_IMAGE:-ubuntu2404i}"
    image: "docker.io/geerlingguy/docker-${MOLECULE_IMAGE:-ubuntu2204i}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true
    cgroupns_mode: host
  - name: "${MOLECULE_IMAGE:-debian12i}"
    image: "docker.io/geerlingguy/docker-${MOLECULE_IMAGE:-debian12i}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true
    cgroupns_mode: host
  - name: "${MOLECULE_IMAGE:-fedora40i}"
    image: "docker.io/geerlingguy/docker-${MOLECULE_IMAGE:-fedora40i}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true
    cgroupns_mode: host
provisioner:
  name: ansible
verifier:
  name: ansible
